### PR TITLE
added aarch64 support

### PR DESCRIPTION
**Pull request by nerohmot**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
@nerohmot you forgot to rerender the feedstock. I did that for you. Let's see if the build works.

**Comment by nerohmot** [comment]
@m-rossi woops ... i rendered on my linux box ... and yes, after commit :-( sorry
curious if it pops up tomorrow on my box, and even more curious to see if it works :-)

**Review by m-rossi — APPROVED** [review]

**Comment by m-rossi** [comment]
Not an issue ;-) thanks for the contribution!

**Pull request merged**
